AMAZON_CREDENTIAL = {
    'AWS_ACCESS_KEY_ID': 'AKIAVZHLZMCYIIAJKR44',
    'AWS_SECRET_ACCESS_KEY': '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',
    'AWS_STORAGE_BUCKET_NAME' : 'mebbscorner001'
}

OTP_KEY = "Some Random Secret Key"

HOST_PASSWORD = 'virtu@ldj1991'