# Generated by Django 3.1.3 on 2020-11-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201106_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='counter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='isVerified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
    ]
