# Generated by Django 3.1.3 on 2020-11-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201106_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Mobile',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=6, null=True),
        ),
    ]
