# Generated by Django 3.1.3 on 2020-12-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20201225_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user_pref',
            field=models.ManyToManyField(related_name='user_engagement', to='accounts.DataTags'),
        ),
    ]
