# Generated by Django 2.2 on 2020-10-11 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_imagegalery_newuploadmultiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegalery',
            name='image_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagegalerys', to='uploads.NewUploadMultiple'),
        ),
        migrations.AlterField(
            model_name='newuploadmultiple',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newuploads',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
