# Generated by Django 2.2 on 2020-10-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20201011_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10, null=True)),
                ('image_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.NewUploadMultiple')),
            ],
        ),
    ]
