# Generated by Django 2.2 on 2020-10-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_likeimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUploads',
        ),
        migrations.AlterField(
            model_name='likeimage',
            name='image_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='uploads.NewUploadMultiple'),
        ),
    ]
