# Generated by Django 2.2 on 2020-10-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_auto_20201012_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegalery',
            name='file_type',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='imagegalery',
            name='image_file',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='likeimage',
            name='image_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_y', to='uploads.NewUploadMultiple'),
        ),
    ]
