# Generated by Django 2.2 on 2020-10-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20201012_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegalery',
            old_name='image_file',
            new_name='media_file',
        ),
    ]
