# Generated by Django 2.2 on 2020-10-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_auto_20201013_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecomment',
            old_name='user',
            new_name='comment_by',
        ),
    ]
