# Generated by Django 2.2 on 2020-10-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_auto_20201013_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_confirmed',
            new_name='phone_confirmed',
        ),
    ]
