# Generated by Django 3.1.3 on 2020-11-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0011_auto_20201013_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
