# Generated by Django 3.1.3 on 2020-11-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0014_auto_20201103_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomment',
            name='comment_by',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
