# Generated by Django 3.1.3 on 2020-11-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0020_newuploadmultiple_commentator'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='likeimage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='newuploadmultiple',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
