# Generated by Django 3.1.3 on 2020-11-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0021_auto_20201109_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecomment',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='likeimage',
            name='created_on',
        ),
    ]
