# Generated by Django 3.1.3 on 2020-11-11 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0023_auto_20201109_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheep', to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sherpherd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
