# Generated by Django 3.1.3 on 2020-11-11 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0025_newuploadmultiple_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancelist',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
