# Generated by Django 3.1.3 on 2020-11-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0027_auto_20201111_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alliancelist',
            old_name='followering',
            new_name='following',
        ),
    ]
