# Generated by Django 3.1.3 on 2020-11-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0028_auto_20201111_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllianceList',
        ),
    ]
