# Generated by Django 3.1.3 on 2020-11-11 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0029_delete_alliancelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheep', to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sherpherd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
