# Generated by Django 3.1.3 on 2020-11-12 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0030_alliancelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_media', to='uploads.newuploadmultiple')),
                ('users_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
