# Generated by Django 3.1.3 on 2020-11-13 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0031_savedmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmedia',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
