# Generated by Django 3.1.3 on 2020-11-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0033_taggeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliancelist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
