# Generated by Django 3.1.3 on 2020-11-23 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0035_statusmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMediaGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='images/')),
                ('file_type', models.CharField(max_length=7, null=True)),
                ('image_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.statusmedia')),
            ],
        ),
    ]
