# Generated by Django 3.1.3 on 2020-11-30 12:11

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0036_statusmediagallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegalery',
            name='media_file',
            field=models.FileField(null=True, upload_to=uploads.models.generate_media_path),
        ),
        migrations.AlterField(
            model_name='statusmediagallery',
            name='media_file',
            field=models.FileField(upload_to=uploads.models.generate_media_path),
        ),
    ]
