# Generated by Django 3.1.3 on 2020-12-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0041_newuploadmultiple_commentable'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegalery',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newuploadmultiple',
            name='detail',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
