# Generated by Django 3.1.3 on 2020-12-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0042_auto_20201208_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuploadmultiple',
            name='detail_url',
            field=models.URLField(max_length=80, null=True),
        ),
    ]
