# Generated by Django 3.1.3 on 2020-12-09 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0043_newuploadmultiple_detail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredUploadMultiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=30, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('sponsored_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_media', to='uploads.newuploadmultiple')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
