# Generated by Django 3.1.3 on 2020-12-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0044_sponsoreduploadmultiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuploadmultiple',
            name='commercial',
            field=models.BooleanField(default=False),
        ),
    ]
