# Generated by Django 3.1.3 on 2020-12-09 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0045_newuploadmultiple_commercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('comment_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_ins', to='uploads.imagecomment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_liked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
