# Generated by Django 3.1.3 on 2020-12-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0047_imagecomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuploadmultiple',
            name='commentator',
        ),
    ]
