# Generated by Django 3.1.3 on 2020-12-25 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0051_newuploadmultiple_mini_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sponsoreduploadmultiple',
            name='expire_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sponsoreduploadmultiple',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AdsStatsDataa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_stat', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
