# Generated by Django 3.1.3 on 2020-12-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0052_auto_20201225_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataTags',
        ),
    ]
