# Generated by Django 3.1.3 on 2020-12-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20201227_1317'),
        ('uploads', '0053_delete_datatags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoreduploadmultiple',
            name='user_pref',
            field=models.ManyToManyField(related_name='user_ads_engagement', to='accounts.DataTags'),
        ),
    ]
