from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home_view'),
    path('search/', views.search_view, name='search_view'),
    path('api_root/', views.api_root, name='api_root'),
    path('special/', views.show_image_fk, name='show_image_fk'),
    path('profile-page/', views.profile_page, name='profile_page'),
    path('profile-page-others/', views.profile_page_others, name='profile_page_others'),
    path('like-image/', views.likeimage, name='likeimage'),
    path('check-upload-status/', views.check_upload_status, name='check_upload_status'),
    path('block-request/', views.block_request, name='block_request'),
    path('follow-request/', views.follow_request, name='follow_request'),
    path('followers-request-display/', views.followers_request_display, name='followers_request_display'),
    path('following-request-display/', views.following_request_display, name='following_request_display'),
    # path('following-request-display/', views.following_request_display, name='following_request_display'),
    path('show-comments/', views.show_comments, name='show_comments'),
    # path('show-saved-media/<int:image_pk>/', views.show_saved_media, name='show_saved_media'),
    path('upload-media/', views.upload_media, name='upload_media'),
    path('show-saved-media/', views.show_saved_media, name='show_saved_media'),
    path('show-specific-saved-media/', views.show_specific_saved_media, name='show_specific_saved_media'),
    path('edit-collection/', views.edit_collection, name='edit_collection'),
    path('delete-collection/', views.delete_collection, name='delete_collection'),
    path('add-collection/', views.add_collection, name='add_collection'),
    path('create-collection/', views.create_collection, name='create_collection'),
    path('upload-media-status/', views.upload_media_status, name='upload_media_status'),
    path('update-media/', views.update_media, name='update_media'),
    path('last-seen/', views.last_seen, name='last_seen'),
    path('save-media/', views.save_media, name='save_media'),
    path('delete-media/', views.delete_media, name='delete_media'),
    path('show-single-media/', views.media_file, name='media_file'),
    path('show-single-media-file/', views.media_file_single, name='media_file_single'),
    path('make-comment/', views.make_comment, name='make_comment'),
    path('like-comment/', views.like_comment, name='like_comment'),
    path('home/', views.home, name='home'),
    path('one/', views.api_root),
    path('show-user/', views.user_show),
]
